Adrien profil profil summary
researchshare-official/frontend pull request #15
Opened 2021-12-09 14:22 UTC by CubeLeopard5

2021-12-11 10:55 UTC, ThalusA requested changes

2021-12-11 10:55 UTC, ThalusA commented on components/Profile/OnePublication.tsx
> +                <Typography variant="subtitle1" sx={{ color: '#7447D5', marginTop: '1%' }}> Adrien Michaud, Adina Cazalens, Alexandre Monnier, Maugan Verdier, Lorenzo Carrascosa </Typography>
```suggestion
                <Typography variant="subtitle1" sx={{ color: 'secondary.main', marginTop: '1%' }}> Adrien Michaud, Adina Cazalens, Alexandre Monnier, Maugan Verdier, Lorenzo Carrascosa </Typography>
```

2021-12-11 10:55 UTC, ThalusA commented on components/Profile/OnePublication.tsx
> +                        <Button variant="contained" sx={{ bgcolor: '#D60000', marginTop: '25%' }}>Remove</Button>
```suggestion
                        <Button variant="contained" sx={{ bgcolor: 'palette.error.main', marginTop: '25%' }}>Remove</Button>
```

2021-12-11 10:55 UTC, ThalusA commented on components/Profile/ProfileContent.tsx
> +                <Typography sx={{ color: '#7447D5', fontSize: '20px' }}>Adina Cazalens</Typography>
```suggestion
                <Typography sx={{ color: 'secondary.main', fontSize: '20px' }}>Adina Cazalens</Typography> 
```

2021-12-15 13:50 UTC, ThalusA requested changes

2021-12-15 13:50 UTC, ThalusA commented on components/Profile/OnePublication.tsx
> +                <Typography variant="subtitle1" sx={{ color: '#7447D5', marginTop: '1%' }}> Adrien Michaud, Adina Cazalens, Alexandre Monnier, Maugan Verdier, Lorenzo Carrascosa </Typography>
```suggestion
                <Typography variant="subtitle1" sx={{ color: 'secondary.main', marginTop: '1%' }}> Adrien Michaud, Adina Cazalens, Alexandre Monnier, Maugan Verdier, Lorenzo Carrascosa </Typography>
```

2021-12-15 13:50 UTC, ThalusA commented on components/Profile/ProfileContent.tsx
> +                <Typography sx={{ color: '#7447D5', fontSize: '20px' }}>Adina Cazalens</Typography>
```suggestion
                <Typography sx={{ color: 'secondary.main', fontSize: '20px' }}>Adina Cazalens</Typography> 
```

2021-12-15 13:54 UTC, ThalusA commented on pages/profile_labo.tsx
> +                    {/* <Summary/> */}
```suggestion
```

2021-12-15 13:55 UTC, ThalusA commented on components/Profile_labo/ProfileContent.tsx
> +            </TabPanel> */}
```suggestion
```

2021-12-16 08:27 UTC, Jerem-b approved these changes

2021-12-16 08:32 UTC, Flavienallix approved these changes

2021-12-16 08:32 UTC, Jerem-b approved these changes

2021-12-16 08:39 UTC, SBasique approved these changes

2021-12-16 10:08 UTC, merged