Page template
researchshare-official/frontend pull request #19
Opened 2021-12-10 15:05 UTC by scriptanium

2021-12-10 15:05 UTC, scriptanium commented
We need to use themes in colors

2021-12-10 15:08 UTC, scriptanium commented
At this state change colors for theme
@CubeLeopard5
We need to choose which article preview because you made some and here is another

2021-12-10 23:40 UTC, ThalusA requested changes

2021-12-10 23:40 UTC, ThalusA commented on components/FilterBar.tsx
> +    border: '3px solid #7447D5',
```suggestion
    border: 'solid',
    borderRadius: 3,
    borderColor: 'secondary.main'
```

2021-12-10 23:40 UTC, ThalusA commented on components/FilterBar.tsx
> +    borderRadius: theme.shape.borderRadius,
```suggestion
```

2021-12-10 23:40 UTC, ThalusA commented on mocking/articles.json
> +                "Alexandre Monnier",
```suggestion
                "Alexandre Monier",
```

2021-12-10 23:40 UTC, ThalusA commented on mocking/hot_articles.json
> +                "Alexandre Monnier",
```suggestion
                "Alexandre Monier",
```

2021-12-16 08:31 UTC, Flavienallix approved these changes

2021-12-16 08:38 UTC, Jerem-b approved these changes

2021-12-16 15:02 UTC, Flavienallix approved these changes

2021-12-16 15:03 UTC, CubeLeopard5 approved these changes
c'est bo

2021-12-16 15:21 UTC, merged